a=input('Input Your first Number:')
b=input('Input Your second Number:')
c=input('Your third Number:')
d=input('Your Number 5:')
e=input('Your Number 6:')
print("Float of 1 Equal %s\n"%float(a))
print("complex of 1 Equal %s\n"%complex(a))
print("Float of 2 Equal %s\n"%float(b))
print("complex of 2 Equal %s\n"%complex(b))
print("Float of 3 Equal %s\n"%float(c))
print("complex of 3 Equal %s\n"%complex(c))
print("Float of 4 Equal %s\n"%float(d))
print("complex of 4 Equal %s\n"%complex(d))
print("Float of 5 Equal %s\n"%float(e))
print("complex of 5 Equal %s\n"%complex(e))