first=input('Input First Number\n')
second=input('Input Second Number\n')
print("{0} = {1} : ".format(first,second),first == second)
print("{0} > {1} : ".format(first,second),first > second)
print("{0} < {1} :".format(first,second),first < second)